//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineHitssAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleto
    {
        public int ID { get; set; }
        public Nullable<int> Funcion_ID { get; set; }
        public Nullable<int> Usuarios_ID { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Funcion Funcion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
