//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineHitssAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcion()
        {
            this.Boletoes = new HashSet<Boleto>();
        }
    
        public int ID { get; set; }
        public string Hora { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Sala { get; set; }
        public Nullable<int> Disponibilidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> Pelicula_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleto> Boletoes { get; set; }
        public virtual Pelicula Pelicula { get; set; }
    }
}
