//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineHitss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pelicula()
        {
            this.Funcions = new HashSet<Funcion>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Genero { get; set; }
        public Nullable<int> Duracion { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> Cine_ID { get; set; }
        public bool Estado { get; set; }
    
        public virtual Cine Cine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcion> Funcions { get; set; }
    }
}
